import { writeFile } from 'node:fs/promises';
import { levels } from '../dist/levels.js';
import { solveDetailed } from '../dist/engine.js';

const data = {};
for (const level of levels.filter(l => l.id >= 11)) {
  const result = solveDetailed(level.board, level.n, level.moves, 20000000);
  if (result.status !== 'solved' || !result.solution.length) throw Error(`No verified hint: ${level.key}`);
  data[level.key] = {
    signature: JSON.stringify([level.n, level.moves, level.board.map(c => c ? [c.v, !!c.star] : null)]),
    path: result.solution[0],
  };
}
await writeFile(new URL('../dist/hint-data.js', import.meta.url), '// Generated by node scripts/generate-hints.mjs. First moves only.\nexport const hintData = ' + JSON.stringify(data, null, 2) + ';\n');
console.log(`Verified first-move hints: ${Object.keys(data).length}`);
