import { readFile, writeFile, cp, mkdir } from 'node:fs/promises';
import { resolve, relative, isAbsolute } from 'node:path';
import { fileURLToPath } from 'node:url';
import { execFileSync } from 'node:child_process';
import { release, publishedSource, nextRelease, preparedLevels } from './shape-content.mjs';
import { levels } from '../dist/levels.js';
import { solveDetailed } from '../dist/engine.js';
import { puzzleSignature } from '../dist/hints.js';

const repo=fileURLToPath(new URL('../',import.meta.url));
const args=process.argv.slice(2);
const value=flag=>args[args.indexOf(flag)+1];
if(args.includes('--check')) {
  if(await readFile(new URL('../dist/published-shapes.js',import.meta.url),'utf8')!==publishedSource(release.publishedThrough))throw Error('Release payload does not match content/release.json');
  if(levels.length!==release.publishedThrough)throw Error('Published stage count mismatch');
  console.log(`Release held at ${release.publishedThrough}; 51–100 prepared in five packs.`);
} else {
  const preview=args.includes('--preview');
  const through=Number(value(preview?'--through':'--to'));
  if(!preview)nextRelease(release.publishedThrough,through);
  const source=publishedSource(through);
  const target=preview?resolve(value('--preview')):resolve(repo,'dist');
  if(preview) {
    // Never allow a developer preview to overwrite a checkout or its public assets.
    const scratch=resolve(repo,'work'),rel=relative(scratch,target);
    if(!rel||rel.startsWith('..')||isAbsolute(rel))throw Error('Preview output must be a subdirectory of repository work/');
  }
  const selected=[...levels.slice(0,50),...preparedLevels.filter(l=>l.id<=through)];
  const data={};
  for(const level of selected.filter(l=>l.id>=11)) {
    const result=solveDetailed(level.board,level.n,level.moves,20000000);
    if(result.status!=='solved')throw Error(`Unverified hint for ${level.key}`);
    data[level.key]={signature:puzzleSignature(level),path:result.solution[0]};
  }
  // All selection/solver checks finish before changing public payloads.
  if(preview){await mkdir(target,{recursive:true});await cp(resolve(repo,'dist'),target,{recursive:true});}
  await writeFile(resolve(target,'published-shapes.js'),source);
  await writeFile(resolve(target,'hint-data.js'),'// Generated by node scripts/generate-hints.mjs. First moves only.\nexport const hintData = '+JSON.stringify(data,null,2)+';\n');
  if(preview) {
    // This entrypoint exists only in the local preview, never in dist or a release.
    const html=await readFile(resolve(target,'index.html'),'utf8');
    await writeFile(resolve(target,'index.html'),html.replace('src="./app.js"','src="./preview-entry.js"'));
    await writeFile(resolve(target,'preview-entry.js'),`import {levels} from './levels.js';\nimport {puzzleSignature} from './hints.js';\nconst stage=Number(new URL(location.href).searchParams.get('stage')||51);\nconst level=levels.find(l=>l.id===stage);\nif(level){localStorage.setItem('sequencepang2-active-v1',JSON.stringify({version:2,key:level.key}));localStorage.setItem('sequenstar-campaign-v2',JSON.stringify(Object.fromEntries(levels.filter(l=>l.id<stage).map(l=>[l.key,true]))));localStorage.setItem('sequencepang2-hints-v1',JSON.stringify({[level.key]:{signature:puzzleSignature(level),failures:5}}));}\nawait import('./app.js');\n`);
    // Disable offline caching in scratch preview so a different test stage is fresh.
    await writeFile(resolve(target,'pwa.js'),'// Local preview only: offline installation disabled.\n');
    console.log(`Local preview through ${through}: ${target}. Production release remains ${release.publishedThrough}.`);
  } else {
    await writeFile(new URL('../content/release.json',import.meta.url),JSON.stringify({...release,publishedThrough:through},null,2)+'\n');
    execFileSync(process.execPath,['scripts/build-sw.mjs'],{cwd:repo,stdio:'inherit'});
    console.log(`Prepared release ${through-9}–${through}. Run npm test, review and deploy only on the owner's instruction. This command does not push or deploy.`);
  }
}
